name: Setup Environment
description: Performs setup of Python and its dependencies
inputs:
  python-version:
    description: 'Python version to run'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'

    - name: Install Unix dependencies
      shell: sh
      run: |
        sudo apt-get -qq update

    - name: Upgrade pip and build dependencies
      shell: sh
      run: |
        python -m pip install --upgrade pip setuptools

    - name: Install Tox
      shell: sh
      run: |
        pip install tox
